language: swift
osx_image: xcode9.2

script:
    - xcodebuild clean build test -sdk iphonesimulator -workspace SuperheroApp.xcworkspace -scheme SuperheroApp  CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.2'
