language: swift
osx_image: xcode9.2

cache:
    - cocoapods

before_install:
    - gem install cocoapods --version 1.4.0

install:
    - pod repo update

script:
    - ./gradlew clean build --refresh-dependencies
